# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _JoystickDataWrapper
else:
    import _JoystickDataWrapper

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _JoystickDataWrapper.delete_SwigPyIterator

    def value(self):
        return _JoystickDataWrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _JoystickDataWrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _JoystickDataWrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _JoystickDataWrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _JoystickDataWrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _JoystickDataWrapper.SwigPyIterator_copy(self)

    def next(self):
        return _JoystickDataWrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _JoystickDataWrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _JoystickDataWrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _JoystickDataWrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _JoystickDataWrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _JoystickDataWrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _JoystickDataWrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _JoystickDataWrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _JoystickDataWrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _JoystickDataWrapper.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _JoystickDataWrapper:
_JoystickDataWrapper.SwigPyIterator_swigregister(SwigPyIterator)

FASTCDR_VERSION_MAJOR = _JoystickDataWrapper.FASTCDR_VERSION_MAJOR
FASTCDR_VERSION_MINOR = _JoystickDataWrapper.FASTCDR_VERSION_MINOR
FASTCDR_VERSION_MICRO = _JoystickDataWrapper.FASTCDR_VERSION_MICRO
FASTCDR_VERSION_STR = _JoystickDataWrapper.FASTCDR_VERSION_STR
HAVE_CXX11 = _JoystickDataWrapper.HAVE_CXX11
FASTCDR_IS_BIG_ENDIAN_TARGET = _JoystickDataWrapper.FASTCDR_IS_BIG_ENDIAN_TARGET
FASTCDR_HAVE_FLOAT128 = _JoystickDataWrapper.FASTCDR_HAVE_FLOAT128
FASTCDR_SIZEOF_LONG_DOUBLE = _JoystickDataWrapper.FASTCDR_SIZEOF_LONG_DOUBLE
import fastdds
class int32_t_vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _JoystickDataWrapper.int32_t_vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _JoystickDataWrapper.int32_t_vector___nonzero__(self)

    def __bool__(self):
        return _JoystickDataWrapper.int32_t_vector___bool__(self)

    def __len__(self):
        return _JoystickDataWrapper.int32_t_vector___len__(self)

    def __getslice__(self, i, j):
        return _JoystickDataWrapper.int32_t_vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _JoystickDataWrapper.int32_t_vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _JoystickDataWrapper.int32_t_vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _JoystickDataWrapper.int32_t_vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _JoystickDataWrapper.int32_t_vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _JoystickDataWrapper.int32_t_vector___setitem__(self, *args)

    def pop(self):
        return _JoystickDataWrapper.int32_t_vector_pop(self)

    def append(self, x):
        return _JoystickDataWrapper.int32_t_vector_append(self, x)

    def empty(self):
        return _JoystickDataWrapper.int32_t_vector_empty(self)

    def size(self):
        return _JoystickDataWrapper.int32_t_vector_size(self)

    def swap(self, v):
        return _JoystickDataWrapper.int32_t_vector_swap(self, v)

    def begin(self):
        return _JoystickDataWrapper.int32_t_vector_begin(self)

    def end(self):
        return _JoystickDataWrapper.int32_t_vector_end(self)

    def rbegin(self):
        return _JoystickDataWrapper.int32_t_vector_rbegin(self)

    def rend(self):
        return _JoystickDataWrapper.int32_t_vector_rend(self)

    def clear(self):
        return _JoystickDataWrapper.int32_t_vector_clear(self)

    def get_allocator(self):
        return _JoystickDataWrapper.int32_t_vector_get_allocator(self)

    def pop_back(self):
        return _JoystickDataWrapper.int32_t_vector_pop_back(self)

    def erase(self, *args):
        return _JoystickDataWrapper.int32_t_vector_erase(self, *args)

    def __init__(self, *args):
        _JoystickDataWrapper.int32_t_vector_swiginit(self, _JoystickDataWrapper.new_int32_t_vector(*args))

    def push_back(self, x):
        return _JoystickDataWrapper.int32_t_vector_push_back(self, x)

    def front(self):
        return _JoystickDataWrapper.int32_t_vector_front(self)

    def back(self):
        return _JoystickDataWrapper.int32_t_vector_back(self)

    def assign(self, n, x):
        return _JoystickDataWrapper.int32_t_vector_assign(self, n, x)

    def resize(self, *args):
        return _JoystickDataWrapper.int32_t_vector_resize(self, *args)

    def insert(self, *args):
        return _JoystickDataWrapper.int32_t_vector_insert(self, *args)

    def reserve(self, n):
        return _JoystickDataWrapper.int32_t_vector_reserve(self, n)

    def capacity(self):
        return _JoystickDataWrapper.int32_t_vector_capacity(self)

    def get_buffer(self):
        return _JoystickDataWrapper.int32_t_vector_get_buffer(self)
    __swig_destroy__ = _JoystickDataWrapper.delete_int32_t_vector

# Register int32_t_vector in _JoystickDataWrapper:
_JoystickDataWrapper.int32_t_vector_swigregister(int32_t_vector)

class double_vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _JoystickDataWrapper.double_vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _JoystickDataWrapper.double_vector___nonzero__(self)

    def __bool__(self):
        return _JoystickDataWrapper.double_vector___bool__(self)

    def __len__(self):
        return _JoystickDataWrapper.double_vector___len__(self)

    def __getslice__(self, i, j):
        return _JoystickDataWrapper.double_vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _JoystickDataWrapper.double_vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _JoystickDataWrapper.double_vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _JoystickDataWrapper.double_vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _JoystickDataWrapper.double_vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _JoystickDataWrapper.double_vector___setitem__(self, *args)

    def pop(self):
        return _JoystickDataWrapper.double_vector_pop(self)

    def append(self, x):
        return _JoystickDataWrapper.double_vector_append(self, x)

    def empty(self):
        return _JoystickDataWrapper.double_vector_empty(self)

    def size(self):
        return _JoystickDataWrapper.double_vector_size(self)

    def swap(self, v):
        return _JoystickDataWrapper.double_vector_swap(self, v)

    def begin(self):
        return _JoystickDataWrapper.double_vector_begin(self)

    def end(self):
        return _JoystickDataWrapper.double_vector_end(self)

    def rbegin(self):
        return _JoystickDataWrapper.double_vector_rbegin(self)

    def rend(self):
        return _JoystickDataWrapper.double_vector_rend(self)

    def clear(self):
        return _JoystickDataWrapper.double_vector_clear(self)

    def get_allocator(self):
        return _JoystickDataWrapper.double_vector_get_allocator(self)

    def pop_back(self):
        return _JoystickDataWrapper.double_vector_pop_back(self)

    def erase(self, *args):
        return _JoystickDataWrapper.double_vector_erase(self, *args)

    def __init__(self, *args):
        _JoystickDataWrapper.double_vector_swiginit(self, _JoystickDataWrapper.new_double_vector(*args))

    def push_back(self, x):
        return _JoystickDataWrapper.double_vector_push_back(self, x)

    def front(self):
        return _JoystickDataWrapper.double_vector_front(self)

    def back(self):
        return _JoystickDataWrapper.double_vector_back(self)

    def assign(self, n, x):
        return _JoystickDataWrapper.double_vector_assign(self, n, x)

    def resize(self, *args):
        return _JoystickDataWrapper.double_vector_resize(self, *args)

    def insert(self, *args):
        return _JoystickDataWrapper.double_vector_insert(self, *args)

    def reserve(self, n):
        return _JoystickDataWrapper.double_vector_reserve(self, n)

    def capacity(self):
        return _JoystickDataWrapper.double_vector_capacity(self)

    def get_buffer(self):
        return _JoystickDataWrapper.double_vector_get_buffer(self)
    __swig_destroy__ = _JoystickDataWrapper.delete_double_vector

# Register double_vector in _JoystickDataWrapper:
_JoystickDataWrapper.double_vector_swigregister(double_vector)

class _JoystickDataSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _JoystickDataWrapper.delete__JoystickDataSeq

# Register _JoystickDataSeq in _JoystickDataWrapper:
_JoystickDataWrapper._JoystickDataSeq_swigregister(_JoystickDataSeq)

class JoystickDataSeq(_JoystickDataSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _JoystickDataWrapper.delete_JoystickDataSeq

    def __init__(self, *args):
        _JoystickDataWrapper.JoystickDataSeq_swiginit(self, _JoystickDataWrapper.new_JoystickDataSeq(*args))

    def __len__(self):
        return _JoystickDataWrapper.JoystickDataSeq___len__(self)

    def __getitem__(self, i):
        return _JoystickDataWrapper.JoystickDataSeq___getitem__(self, i)

# Register JoystickDataSeq in _JoystickDataWrapper:
_JoystickDataWrapper.JoystickDataSeq_swigregister(JoystickDataSeq)

class JoystickData(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _JoystickDataWrapper.delete_JoystickData

    def __init__(self, *args):
        _JoystickDataWrapper.JoystickData_swiginit(self, _JoystickDataWrapper.new_JoystickData(*args))

    def __eq__(self, x):
        return _JoystickDataWrapper.JoystickData___eq__(self, x)

    def __ne__(self, x):
        return _JoystickDataWrapper.JoystickData___ne__(self, x)

    def buttonStates(self, *args):
        return _JoystickDataWrapper.JoystickData_buttonStates(self, *args)

    def axisStates(self, *args):
        return _JoystickDataWrapper.JoystickData_axisStates(self, *args)

    def hatStates(self, *args):
        return _JoystickDataWrapper.JoystickData_hatStates(self, *args)

# Register JoystickData in _JoystickDataWrapper:
_JoystickDataWrapper.JoystickData_swigregister(JoystickData)

GEN_API_VER = _JoystickDataWrapper.GEN_API_VER
class JoystickDataPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _JoystickDataWrapper.JoystickDataPubSubType_swiginit(self, _JoystickDataWrapper.new_JoystickDataPubSubType())
    __swig_destroy__ = _JoystickDataWrapper.delete_JoystickDataPubSubType

    def serialize(self, *args):
        return _JoystickDataWrapper.JoystickDataPubSubType_serialize(self, *args)

    def deserialize(self, payload, data):
        return _JoystickDataWrapper.JoystickDataPubSubType_deserialize(self, payload, data)

    def getSerializedSizeProvider(self, *args):
        return _JoystickDataWrapper.JoystickDataPubSubType_getSerializedSizeProvider(self, *args)

    def getKey(self, data, ihandle, force_md5=False):
        return _JoystickDataWrapper.JoystickDataPubSubType_getKey(self, data, ihandle, force_md5)

    def createData(self):
        return _JoystickDataWrapper.JoystickDataPubSubType_createData(self)

    def deleteData(self, data):
        return _JoystickDataWrapper.JoystickDataPubSubType_deleteData(self, data)

    def is_bounded(self):
        return _JoystickDataWrapper.JoystickDataPubSubType_is_bounded(self)

    def is_plain(self, *args):
        return _JoystickDataWrapper.JoystickDataPubSubType_is_plain(self, *args)

    def construct_sample(self, memory):
        return _JoystickDataWrapper.JoystickDataPubSubType_construct_sample(self, memory)
    m_md5 = property(_JoystickDataWrapper.JoystickDataPubSubType_m_md5_get, _JoystickDataWrapper.JoystickDataPubSubType_m_md5_set)
    m_keyBuffer = property(_JoystickDataWrapper.JoystickDataPubSubType_m_keyBuffer_get, _JoystickDataWrapper.JoystickDataPubSubType_m_keyBuffer_set)

# Register JoystickDataPubSubType in _JoystickDataWrapper:
_JoystickDataWrapper.JoystickDataPubSubType_swigregister(JoystickDataPubSubType)



