// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Query_msg.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Query_msg.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>




Query_msg::Query_msg()
{
}

Query_msg::~Query_msg()
{
}

Query_msg::Query_msg(
        const Query_msg& x)
{
    m_slave_id = x.m_slave_id;
    m_func_code = x.m_func_code;
    m_write_addr = x.m_write_addr;
    m_read_addr = x.m_read_addr;
    m_write_num = x.m_write_num;
    m_read_num = x.m_read_num;
    m_data = x.m_data;
}

Query_msg::Query_msg(
        Query_msg&& x) noexcept
{
    m_slave_id = x.m_slave_id;
    m_func_code = x.m_func_code;
    m_write_addr = x.m_write_addr;
    m_read_addr = x.m_read_addr;
    m_write_num = x.m_write_num;
    m_read_num = x.m_read_num;
    m_data = std::move(x.m_data);
}

Query_msg& Query_msg::operator =(
        const Query_msg& x)
{

    m_slave_id = x.m_slave_id;
    m_func_code = x.m_func_code;
    m_write_addr = x.m_write_addr;
    m_read_addr = x.m_read_addr;
    m_write_num = x.m_write_num;
    m_read_num = x.m_read_num;
    m_data = x.m_data;
    return *this;
}

Query_msg& Query_msg::operator =(
        Query_msg&& x) noexcept
{

    m_slave_id = x.m_slave_id;
    m_func_code = x.m_func_code;
    m_write_addr = x.m_write_addr;
    m_read_addr = x.m_read_addr;
    m_write_num = x.m_write_num;
    m_read_num = x.m_read_num;
    m_data = std::move(x.m_data);
    return *this;
}

bool Query_msg::operator ==(
        const Query_msg& x) const
{
    return (m_slave_id == x.m_slave_id &&
           m_func_code == x.m_func_code &&
           m_write_addr == x.m_write_addr &&
           m_read_addr == x.m_read_addr &&
           m_write_num == x.m_write_num &&
           m_read_num == x.m_read_num &&
           m_data == x.m_data);
}

bool Query_msg::operator !=(
        const Query_msg& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member slave_id
 * @param _slave_id New value for member slave_id
 */
void Query_msg::slave_id(
        uint32_t _slave_id)
{
    m_slave_id = _slave_id;
}

/*!
 * @brief This function returns the value of member slave_id
 * @return Value of member slave_id
 */
uint32_t Query_msg::slave_id() const
{
    return m_slave_id;
}

/*!
 * @brief This function returns a reference to member slave_id
 * @return Reference to member slave_id
 */
uint32_t& Query_msg::slave_id()
{
    return m_slave_id;
}


/*!
 * @brief This function sets a value in member func_code
 * @param _func_code New value for member func_code
 */
void Query_msg::func_code(
        uint32_t _func_code)
{
    m_func_code = _func_code;
}

/*!
 * @brief This function returns the value of member func_code
 * @return Value of member func_code
 */
uint32_t Query_msg::func_code() const
{
    return m_func_code;
}

/*!
 * @brief This function returns a reference to member func_code
 * @return Reference to member func_code
 */
uint32_t& Query_msg::func_code()
{
    return m_func_code;
}


/*!
 * @brief This function sets a value in member write_addr
 * @param _write_addr New value for member write_addr
 */
void Query_msg::write_addr(
        uint32_t _write_addr)
{
    m_write_addr = _write_addr;
}

/*!
 * @brief This function returns the value of member write_addr
 * @return Value of member write_addr
 */
uint32_t Query_msg::write_addr() const
{
    return m_write_addr;
}

/*!
 * @brief This function returns a reference to member write_addr
 * @return Reference to member write_addr
 */
uint32_t& Query_msg::write_addr()
{
    return m_write_addr;
}


/*!
 * @brief This function sets a value in member read_addr
 * @param _read_addr New value for member read_addr
 */
void Query_msg::read_addr(
        uint32_t _read_addr)
{
    m_read_addr = _read_addr;
}

/*!
 * @brief This function returns the value of member read_addr
 * @return Value of member read_addr
 */
uint32_t Query_msg::read_addr() const
{
    return m_read_addr;
}

/*!
 * @brief This function returns a reference to member read_addr
 * @return Reference to member read_addr
 */
uint32_t& Query_msg::read_addr()
{
    return m_read_addr;
}


/*!
 * @brief This function sets a value in member write_num
 * @param _write_num New value for member write_num
 */
void Query_msg::write_num(
        uint32_t _write_num)
{
    m_write_num = _write_num;
}

/*!
 * @brief This function returns the value of member write_num
 * @return Value of member write_num
 */
uint32_t Query_msg::write_num() const
{
    return m_write_num;
}

/*!
 * @brief This function returns a reference to member write_num
 * @return Reference to member write_num
 */
uint32_t& Query_msg::write_num()
{
    return m_write_num;
}


/*!
 * @brief This function sets a value in member read_num
 * @param _read_num New value for member read_num
 */
void Query_msg::read_num(
        uint32_t _read_num)
{
    m_read_num = _read_num;
}

/*!
 * @brief This function returns the value of member read_num
 * @return Value of member read_num
 */
uint32_t Query_msg::read_num() const
{
    return m_read_num;
}

/*!
 * @brief This function returns a reference to member read_num
 * @return Reference to member read_num
 */
uint32_t& Query_msg::read_num()
{
    return m_read_num;
}


/*!
 * @brief This function copies the value in member data
 * @param _data New value to be copied in member data
 */
void Query_msg::data(
        const std::array<uint32_t, 64>& _data)
{
    m_data = _data;
}

/*!
 * @brief This function moves the value in member data
 * @param _data New value to be moved in member data
 */
void Query_msg::data(
        std::array<uint32_t, 64>&& _data)
{
    m_data = std::move(_data);
}

/*!
 * @brief This function returns a constant reference to member data
 * @return Constant reference to member data
 */
const std::array<uint32_t, 64>& Query_msg::data() const
{
    return m_data;
}

/*!
 * @brief This function returns a reference to member data
 * @return Reference to member data
 */
std::array<uint32_t, 64>& Query_msg::data()
{
    return m_data;
}


// Include auxiliary functions like for serializing/deserializing.
#include "Query_msgCdrAux.ipp"

