// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Response_msg.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_RESPONSE_MSG_H_
#define _FAST_DDS_GENERATED_RESPONSE_MSG_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(RESPONSE_MSG_SOURCE)
#define RESPONSE_MSG_DllAPI __declspec( dllexport )
#else
#define RESPONSE_MSG_DllAPI __declspec( dllimport )
#endif // RESPONSE_MSG_SOURCE
#else
#define RESPONSE_MSG_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define RESPONSE_MSG_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima





/*!
 * @brief This class represents the structure Response_msg defined by the user in the IDL file.
 * @ingroup Response_msg
 */
class Response_msg
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Response_msg();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Response_msg();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Response_msg that will be copied.
     */
    eProsima_user_DllExport Response_msg(
            const Response_msg& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Response_msg that will be copied.
     */
    eProsima_user_DllExport Response_msg(
            Response_msg&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Response_msg that will be copied.
     */
    eProsima_user_DllExport Response_msg& operator =(
            const Response_msg& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Response_msg that will be copied.
     */
    eProsima_user_DllExport Response_msg& operator =(
            Response_msg&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Response_msg object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Response_msg& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Response_msg object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Response_msg& x) const;

    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    eProsima_user_DllExport void data(
            const std::array<uint32_t, 64>& _data);

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    eProsima_user_DllExport void data(
            std::array<uint32_t, 64>&& _data);

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    eProsima_user_DllExport const std::array<uint32_t, 64>& data() const;

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport std::array<uint32_t, 64>& data();


    /*!
     * @brief This function sets a value in member slave_id
     * @param _slave_id New value for member slave_id
     */
    eProsima_user_DllExport void slave_id(
            uint32_t _slave_id);

    /*!
     * @brief This function returns the value of member slave_id
     * @return Value of member slave_id
     */
    eProsima_user_DllExport uint32_t slave_id() const;

    /*!
     * @brief This function returns a reference to member slave_id
     * @return Reference to member slave_id
     */
    eProsima_user_DllExport uint32_t& slave_id();


    /*!
     * @brief This function sets a value in member func_code
     * @param _func_code New value for member func_code
     */
    eProsima_user_DllExport void func_code(
            uint32_t _func_code);

    /*!
     * @brief This function returns the value of member func_code
     * @return Value of member func_code
     */
    eProsima_user_DllExport uint32_t func_code() const;

    /*!
     * @brief This function returns a reference to member func_code
     * @return Reference to member func_code
     */
    eProsima_user_DllExport uint32_t& func_code();

private:

    std::array<uint32_t, 64> m_data{0};
    uint32_t m_slave_id{0};
    uint32_t m_func_code{0};

};

#endif // _FAST_DDS_GENERATED_RESPONSE_MSG_H_



