# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _Response_msgWrapper
else:
    import _Response_msgWrapper

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Response_msgWrapper.delete_SwigPyIterator

    def value(self):
        return _Response_msgWrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _Response_msgWrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _Response_msgWrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _Response_msgWrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _Response_msgWrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _Response_msgWrapper.SwigPyIterator_copy(self)

    def next(self):
        return _Response_msgWrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _Response_msgWrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _Response_msgWrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _Response_msgWrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _Response_msgWrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _Response_msgWrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _Response_msgWrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _Response_msgWrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _Response_msgWrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _Response_msgWrapper.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _Response_msgWrapper:
_Response_msgWrapper.SwigPyIterator_swigregister(SwigPyIterator)

FASTCDR_VERSION_MAJOR = _Response_msgWrapper.FASTCDR_VERSION_MAJOR
FASTCDR_VERSION_MINOR = _Response_msgWrapper.FASTCDR_VERSION_MINOR
FASTCDR_VERSION_MICRO = _Response_msgWrapper.FASTCDR_VERSION_MICRO
FASTCDR_VERSION_STR = _Response_msgWrapper.FASTCDR_VERSION_STR
HAVE_CXX11 = _Response_msgWrapper.HAVE_CXX11
FASTCDR_IS_BIG_ENDIAN_TARGET = _Response_msgWrapper.FASTCDR_IS_BIG_ENDIAN_TARGET
FASTCDR_HAVE_FLOAT128 = _Response_msgWrapper.FASTCDR_HAVE_FLOAT128
FASTCDR_SIZEOF_LONG_DOUBLE = _Response_msgWrapper.FASTCDR_SIZEOF_LONG_DOUBLE
import fastdds
class uint32_t_64_array(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _Response_msgWrapper.uint32_t_64_array_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _Response_msgWrapper.uint32_t_64_array___nonzero__(self)

    def __bool__(self):
        return _Response_msgWrapper.uint32_t_64_array___bool__(self)

    def __len__(self):
        return _Response_msgWrapper.uint32_t_64_array___len__(self)

    def __getslice__(self, i, j):
        return _Response_msgWrapper.uint32_t_64_array___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _Response_msgWrapper.uint32_t_64_array___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _Response_msgWrapper.uint32_t_64_array___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _Response_msgWrapper.uint32_t_64_array___delitem__(self, *args)

    def __getitem__(self, *args):
        return _Response_msgWrapper.uint32_t_64_array___getitem__(self, *args)

    def __setitem__(self, *args):
        return _Response_msgWrapper.uint32_t_64_array___setitem__(self, *args)

    def __init__(self, *args):
        _Response_msgWrapper.uint32_t_64_array_swiginit(self, _Response_msgWrapper.new_uint32_t_64_array(*args))

    def empty(self):
        return _Response_msgWrapper.uint32_t_64_array_empty(self)

    def size(self):
        return _Response_msgWrapper.uint32_t_64_array_size(self)

    def swap(self, v):
        return _Response_msgWrapper.uint32_t_64_array_swap(self, v)

    def begin(self):
        return _Response_msgWrapper.uint32_t_64_array_begin(self)

    def end(self):
        return _Response_msgWrapper.uint32_t_64_array_end(self)

    def rbegin(self):
        return _Response_msgWrapper.uint32_t_64_array_rbegin(self)

    def rend(self):
        return _Response_msgWrapper.uint32_t_64_array_rend(self)

    def front(self):
        return _Response_msgWrapper.uint32_t_64_array_front(self)

    def back(self):
        return _Response_msgWrapper.uint32_t_64_array_back(self)

    def fill(self, u):
        return _Response_msgWrapper.uint32_t_64_array_fill(self, u)

    def get_buffer(self):
        return _Response_msgWrapper.uint32_t_64_array_get_buffer(self)
    __swig_destroy__ = _Response_msgWrapper.delete_uint32_t_64_array

# Register uint32_t_64_array in _Response_msgWrapper:
_Response_msgWrapper.uint32_t_64_array_swigregister(uint32_t_64_array)

class _Response_msgSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Response_msgWrapper.delete__Response_msgSeq

# Register _Response_msgSeq in _Response_msgWrapper:
_Response_msgWrapper._Response_msgSeq_swigregister(_Response_msgSeq)

class Response_msgSeq(_Response_msgSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _Response_msgWrapper.delete_Response_msgSeq

    def __init__(self, *args):
        _Response_msgWrapper.Response_msgSeq_swiginit(self, _Response_msgWrapper.new_Response_msgSeq(*args))

    def __len__(self):
        return _Response_msgWrapper.Response_msgSeq___len__(self)

    def __getitem__(self, i):
        return _Response_msgWrapper.Response_msgSeq___getitem__(self, i)

# Register Response_msgSeq in _Response_msgWrapper:
_Response_msgWrapper.Response_msgSeq_swigregister(Response_msgSeq)

class Response_msg(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _Response_msgWrapper.delete_Response_msg

    def __init__(self, *args):
        _Response_msgWrapper.Response_msg_swiginit(self, _Response_msgWrapper.new_Response_msg(*args))

    def __eq__(self, x):
        return _Response_msgWrapper.Response_msg___eq__(self, x)

    def __ne__(self, x):
        return _Response_msgWrapper.Response_msg___ne__(self, x)

    def data(self, *args):
        return _Response_msgWrapper.Response_msg_data(self, *args)

    def slave_id(self, *args):
        return _Response_msgWrapper.Response_msg_slave_id(self, *args)

    def func_code(self, *args):
        return _Response_msgWrapper.Response_msg_func_code(self, *args)

# Register Response_msg in _Response_msgWrapper:
_Response_msgWrapper.Response_msg_swigregister(Response_msg)

GEN_API_VER = _Response_msgWrapper.GEN_API_VER
class Response_msgPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Response_msgWrapper.Response_msgPubSubType_swiginit(self, _Response_msgWrapper.new_Response_msgPubSubType())
    __swig_destroy__ = _Response_msgWrapper.delete_Response_msgPubSubType

    def serialize(self, *args):
        return _Response_msgWrapper.Response_msgPubSubType_serialize(self, *args)

    def deserialize(self, payload, data):
        return _Response_msgWrapper.Response_msgPubSubType_deserialize(self, payload, data)

    def getSerializedSizeProvider(self, *args):
        return _Response_msgWrapper.Response_msgPubSubType_getSerializedSizeProvider(self, *args)

    def getKey(self, data, ihandle, force_md5=False):
        return _Response_msgWrapper.Response_msgPubSubType_getKey(self, data, ihandle, force_md5)

    def createData(self):
        return _Response_msgWrapper.Response_msgPubSubType_createData(self)

    def deleteData(self, data):
        return _Response_msgWrapper.Response_msgPubSubType_deleteData(self, data)

    def is_bounded(self):
        return _Response_msgWrapper.Response_msgPubSubType_is_bounded(self)

    def is_plain(self, *args):
        return _Response_msgWrapper.Response_msgPubSubType_is_plain(self, *args)

    def construct_sample(self, memory):
        return _Response_msgWrapper.Response_msgPubSubType_construct_sample(self, memory)
    m_md5 = property(_Response_msgWrapper.Response_msgPubSubType_m_md5_get, _Response_msgWrapper.Response_msgPubSubType_m_md5_set)
    m_keyBuffer = property(_Response_msgWrapper.Response_msgPubSubType_m_keyBuffer_get, _Response_msgWrapper.Response_msgPubSubType_m_keyBuffer_set)

# Register Response_msgPubSubType in _Response_msgWrapper:
_Response_msgWrapper.Response_msgPubSubType_swigregister(Response_msgPubSubType)



