# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _State_msgWrapper
else:
    import _State_msgWrapper

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _State_msgWrapper.delete_SwigPyIterator

    def value(self):
        return _State_msgWrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _State_msgWrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _State_msgWrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _State_msgWrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _State_msgWrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _State_msgWrapper.SwigPyIterator_copy(self)

    def next(self):
        return _State_msgWrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _State_msgWrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _State_msgWrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _State_msgWrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _State_msgWrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _State_msgWrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _State_msgWrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _State_msgWrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _State_msgWrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _State_msgWrapper.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _State_msgWrapper:
_State_msgWrapper.SwigPyIterator_swigregister(SwigPyIterator)

FASTCDR_VERSION_MAJOR = _State_msgWrapper.FASTCDR_VERSION_MAJOR
FASTCDR_VERSION_MINOR = _State_msgWrapper.FASTCDR_VERSION_MINOR
FASTCDR_VERSION_MICRO = _State_msgWrapper.FASTCDR_VERSION_MICRO
FASTCDR_VERSION_STR = _State_msgWrapper.FASTCDR_VERSION_STR
HAVE_CXX11 = _State_msgWrapper.HAVE_CXX11
FASTCDR_IS_BIG_ENDIAN_TARGET = _State_msgWrapper.FASTCDR_IS_BIG_ENDIAN_TARGET
FASTCDR_HAVE_FLOAT128 = _State_msgWrapper.FASTCDR_HAVE_FLOAT128
FASTCDR_SIZEOF_LONG_DOUBLE = _State_msgWrapper.FASTCDR_SIZEOF_LONG_DOUBLE
import fastdds
class _State_msgSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _State_msgWrapper.delete__State_msgSeq

# Register _State_msgSeq in _State_msgWrapper:
_State_msgWrapper._State_msgSeq_swigregister(_State_msgSeq)

class State_msgSeq(_State_msgSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _State_msgWrapper.delete_State_msgSeq

    def __init__(self, *args):
        _State_msgWrapper.State_msgSeq_swiginit(self, _State_msgWrapper.new_State_msgSeq(*args))

    def __len__(self):
        return _State_msgWrapper.State_msgSeq___len__(self)

    def __getitem__(self, i):
        return _State_msgWrapper.State_msgSeq___getitem__(self, i)

# Register State_msgSeq in _State_msgWrapper:
_State_msgWrapper.State_msgSeq_swigregister(State_msgSeq)

class State_msg(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _State_msgWrapper.delete_State_msg

    def __init__(self, *args):
        _State_msgWrapper.State_msg_swiginit(self, _State_msgWrapper.new_State_msg(*args))

    def __eq__(self, x):
        return _State_msgWrapper.State_msg___eq__(self, x)

    def __ne__(self, x):
        return _State_msgWrapper.State_msg___ne__(self, x)

    def state_driver(self, *args):
        return _State_msgWrapper.State_msg_state_driver(self, *args)

    def state_mes(self, *args):
        return _State_msgWrapper.State_msg_state_mes(self, *args)

    def state_error(self, *args):
        return _State_msgWrapper.State_msg_state_error(self, *args)

# Register State_msg in _State_msgWrapper:
_State_msgWrapper.State_msg_swigregister(State_msg)

GEN_API_VER = _State_msgWrapper.GEN_API_VER
class State_msgPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _State_msgWrapper.State_msgPubSubType_swiginit(self, _State_msgWrapper.new_State_msgPubSubType())
    __swig_destroy__ = _State_msgWrapper.delete_State_msgPubSubType

    def serialize(self, *args):
        return _State_msgWrapper.State_msgPubSubType_serialize(self, *args)

    def deserialize(self, payload, data):
        return _State_msgWrapper.State_msgPubSubType_deserialize(self, payload, data)

    def getSerializedSizeProvider(self, *args):
        return _State_msgWrapper.State_msgPubSubType_getSerializedSizeProvider(self, *args)

    def getKey(self, data, ihandle, force_md5=False):
        return _State_msgWrapper.State_msgPubSubType_getKey(self, data, ihandle, force_md5)

    def createData(self):
        return _State_msgWrapper.State_msgPubSubType_createData(self)

    def deleteData(self, data):
        return _State_msgWrapper.State_msgPubSubType_deleteData(self, data)

    def is_bounded(self):
        return _State_msgWrapper.State_msgPubSubType_is_bounded(self)

    def is_plain(self, *args):
        return _State_msgWrapper.State_msgPubSubType_is_plain(self, *args)

    def construct_sample(self, memory):
        return _State_msgWrapper.State_msgPubSubType_construct_sample(self, memory)
    m_md5 = property(_State_msgWrapper.State_msgPubSubType_m_md5_get, _State_msgWrapper.State_msgPubSubType_m_md5_set)
    m_keyBuffer = property(_State_msgWrapper.State_msgPubSubType_m_keyBuffer_get, _State_msgWrapper.State_msgPubSubType_m_keyBuffer_set)

# Register State_msgPubSubType in _State_msgWrapper:
_State_msgWrapper.State_msgPubSubType_swigregister(State_msgPubSubType)



